image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r vignettes/Report/* public
    - cp -r vignettes/Results public
  artifacts:
    paths:
     - public
  only:
    - master

