image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - mkdir Results
    - cp -r vignettes/Report/* public
    - cp -r vignettes/Results/* Results
  artifacts:
    paths:
     - public
  only:
    - master

