image: rocker/verse:4.0.4

pages:
  script:
    - installGithub.r gadenbuie/xaringanExtra
    - R -e "install.packages('knitr')"
    - R -e "install.packages('dplyr')"
    - R -e "install.packages('DT')"
    - Rscript -e "bookdown::render_book('index.Rmd', output_dir = 'public')"
  artifacts:
    paths:
     - public
  only:
    - master

