---
urlcolor: blue
link-citations: yes
output: 
  bookdown::pdf_document2:
    keep_tex: false
    citation_package: natbib
    fig_caption: yes
    includes:
      in_header: "/home/rstudio/inst/style/header.tex"
      before_body: "/home/rstudio/inst/style//before_body.tex"
      after_body: "/home/rstudio/inst/style//after_body.tex"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Introduction

The ANCA-associated vasculitides are rare but severe autoimmune disorders. Tools for improved diagnostics and prognostics are needed. In this project, 184 proteins (Olink; CARDIOVASCULAR III and INFLAMMATION panels) and four additional proteins (Luminex data) were measured in serum or plasma samples from patients with ANCA-associated vasculitis and several controls (healthy, remission, disease control), in order to identify biomarkers for active disease, organ involvement and accurate diagnosis.

To accomplish this, following analyses have been agreed upon:

* Quality Control of PEA data
* Unsupervised analysis of data structure using PCA
* Differential expression of first set of samples comparing selected subgroups:
  - Active AAV vs Healthy
  - Active AAV vs Remission AAV
  - Active AAV vs Disease Control
  - GPA vs MPA 
  - MPO-ANCA+ vs PR3-ANCA+
  - (Comparison between affected organs)
* Serum and plasma Samples will be analyzed separately
* Pathway analysis of differential expressed proteins using KEGG, GO, MsigDB, ... gene set collections
* Correlation of proteins with the inflammation markers and BVAS scores
* Effect of cortisone treatment on protein expression
* Biomarkers/Predictors of GPA vs MPA and MPO-ANCA+ vs PR3-ANCA+ (using appropriate ML techniques)

**This report describes the performed analyses and a selection of the resulting output of the plasma results only. The full results and all plots are found in the accompanying Results folder.**

# Data Cleaning

## Clinical Data

The metadata for the separate subgroups was combined into a single metadata dataframe per tissue. Column names were cleaned and made consistent between the different subgroups to allow for easier handling in R. Further cleaning of the dates was performed in R using the *lubridate* package and annotations such as age, time in freezer, BVAS score and site of sample origin were added as well. Samples with no NPX data were removed from the metadata of plasma ("lun1065") and/or serum (("lin113", "sle_121/a" and "sle_156/a").

The resulting metadata for serum and plasma separately is saved in the folder **Results/Plasma/plasma_metadata.csv** and **Results/Serum/serum_metadata.csv** respectively.
